# Generated by Django 3.1.2 on 2020-11-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
